
CREATE TABLE CONTACT (
    CONTACT_ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
    FIRST_NAME varchar(255) NOT NULL,
    LAST_NAME varchar(255) NOT NULL
);

insert into CONTACT (CONTACT_ID, FIRST_NAME, LAST_NAME) values (1, 'Dave', 'Syer');
insert into CONTACT (CONTACT_ID, FIRST_NAME, LAST_NAME) values (2, 'Alexandr', 'Orlov');
insert into CONTACT (CONTACT_ID, FIRST_NAME, LAST_NAME) values (3, 'Kirill', 'Afanasjev');

CREATE TABLE APPLICATION (
    APPLICATION_ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
    CONTACT_ID BIGINT NOT NULL,
    DT_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRODUCT_NAME VARCHAR(255) NOT NULL
);

insert into APPLICATION (CONTACT_ID, DT_CREATED, PRODUCT_NAME) values (1, '2018-01-02 11:12:13', 'AB Test');
insert into APPLICATION (CONTACT_ID, DT_CREATED, PRODUCT_NAME) values (1, '2018-01-02 11:12:14', 'AX Test');
insert into APPLICATION (CONTACT_ID, DT_CREATED, PRODUCT_NAME) values (1, '2018-01-02 11:12:15', 'AY Test');

insert into APPLICATION (CONTACT_ID, DT_CREATED, PRODUCT_NAME) values (2, '2018-01-03 11:12:13', 'BB Test');
insert into APPLICATION (CONTACT_ID, DT_CREATED, PRODUCT_NAME) values (2, '2018-01-03 11:12:14', 'BX Test');
insert into APPLICATION (CONTACT_ID, DT_CREATED, PRODUCT_NAME) values (2, '2018-01-03 11:12:15', 'BY Test');


CREATE TABLE reset_matched_qty_info_response (
    isin VARCHAR(255),
    contract_id VARCHAR(255),
    class_code varchar(255),
    buy_trade_num VARCHAR(255),
    buy_trade_date DATE,
    sell_trade_num VARCHAR(255),
    sell_trade_date DATE,
    qty NUMERIC,
);

insert into reset_matched_qty_info_response(isin, contract_id, class_code, buy_trade_num,    buy_trade_date,  sell_trade_num,      sell_trade_date, qty)
    values ('2000256095', 'US22788C1053', '7', 'SC191014000000000031', '2019-10-14', 'SC191011000000000097', '2019-10-11', 85 );